---
title: "debugging"
author: "Brandon Tat"
date: "4/23/2020"
output: html_document
---

```{r setup, include=FALSE}
library(canvasser)
library(rvest)
library(stringr)
library(dplyr)
```


```{r}
  grade_table <- calc_grade_per_category(scrape_html_for_grades("csc225.html"))
  class(grade_table)
  worth_vector <- c(40,26)
  WORTH <- as.data.frame(as.numeric(worth_vector) / sum(as.numeric(worth_vector)))
  colnames(WORTH) <- "WORTH"

  updated_table <- as_tibble(cbind(grade_table, WORTH))
  class(updated_table)
```



```{r}

  actual <- calc_worth_per_category(calc_grade_per_category(scrape_html_for_grades("csc225.html")), c(40,26))
  expected <- readr::read_csv("calc_worth_per_category_df_testcase.csv")
  testthat::expect_equal(actual, expected)
```



```{r}
  get_html_element <- function(html_filename, element) {

  webpage <- read_html(html_filename)
  asgns_html <- html_nodes(webpage, element)
  asgns_text <- html_text(asgns_html)
  
  return(asgns_text)
  }
  
  assignments <- scrape_asgns("csc225.html")
  total_grades <- scrape_total_points("csc225.html")
  your_grades <- scrape_asgn_grades("csc225.html")


  finished_asgn_table <- cbind(assignments, your_grades, total_grades) %>% 
    as_tibble()
  
  finished_asgn_table
  class(finished_asgn_table)
  
  
```

    %>%
    str_extract("[:digit:]+") %>%
    as.numeric() %>%
    as.data.frame()
  

```{r}
  webpage <- read_html("csc225.html")

  asgn_scores_html <- html_nodes(webpage,'.grade')

  asgn_scores_text <- html_text(asgn_scores_html)
  

  asgn_grades <- str_remove_all(asgn_scores_text, "\\n") %>%
    str_trim() %>%
    str_c(collapse = "\n") %>%
    str_split("\\n") %>%
    unlist() %>%
    str_subset("Click to test a different score") 
  
  asgn_grades

  colnames(asgn_grades) <- "GRADE_EARNED"
```

```{r}
  webpage <- read_html("Grades for Test Student_ kbodwin-sandbox.html")

  asgn_scores_html <- html_nodes(webpage,'.grade')

  asgn_scores_text <- html_text(asgn_scores_html)
  

  asgn_grades <- str_remove_all(asgn_scores_text, "\\n") %>%
    str_trim() %>%
    str_c(collapse = "\n") %>%
    str_split("\\n") %>%
    unlist() %>% 
    str_replace("Instructor is working on grades", "Click to test a different score -") %>% 
    str_subset("Click to test a different score") %>%
    str_extract("[:digit:]+") %>% 
    as.numeric() %>%
    as.data.frame()
  
  colnames(asgn_grades) <- "GRADE_EARNED"

  asgn_grades

  scrape_total_points("Grades for Test Student_ kbodwin-sandbox.html")

```


```{r}
  webpage <- read_html("Grades for Test Student_ kbodwin-sandbox.html")

  total_points_html <- html_nodes(webpage,'.points_possible')
  total_points_text <- html_text(total_points_html)

  total_points_text
  
  total_points_list <- str_remove_all(total_points_text, "\\n") %>%
    str_trim() %>%
    unlist()

  total_points <- as.data.frame(total_points_list[total_points_list != ""]) %>%
    filter(!(str_detect(total_points_list[total_points_list != ""], "/")))

  #colnames(total_points) <- "TOTAL_POINTS"
  #$TOTAL_POINTS <- as.numeric(as.character(total_points$TOTAL_POINTS))
```



```{r}
grades <- scrape_html_for_grades("Grades for Test Student_ kbodwin-sandbox.html")

category_grades <- calc_grade_per_category(grades)

worth_grades <- calc_worth_per_category(category_grades, c(40,26))

bootleg_rogerhub(worth_grades, 36, 93)

scrape_asgn_grades("csc225.html")
```

